import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Explicitly defined rather than autogenerated, so section order is a deliberate
 * reading path (set up -> understand -> call -> extend) instead of alphabetical.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/configuration',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        'api/swagger',
        'api/postman',
        'api/authentication',
        'api/users',
        'api/posts',
        'api/comments',
        'api/likes',
        'api/pagination',
        'api/errors',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/security',
        'architecture/scheduled-tasks',
      ],
    },
    {
      type: 'category',
      label: 'Data Model',
      items: ['data-model/schema'],
    },
    {
      type: 'category',
      label: 'Testing',
      items: ['testing/mockito-suite'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/known-issues',
        'reference/links',
      ],
    },
  ],
};

export default sidebars;
